In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [21]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [24]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [27]:
ann = tf.keras.models.Sequential()

Creating Input layer1 and Input Layer2

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

Creating Output Layer

In [32]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

Traning the model

In [35]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy' ,metrics = ['accuracy'] )

In [36]:
ann.fit(x_train,y_train,batch_size= 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6109 - accuracy: 0.7201
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4710 - accuracy: 0.7975
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4322 - accuracy: 0.8069
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4064 - accuracy: 0.8213
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3911 - accuracy: 0.8330
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3817 - accuracy: 0.8400
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8429
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3713 - accuracy: 0.8436
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3674 - accuracy: 0.8469
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3637 - accura